import sys

from cffi import FFI

ffi = FFI()
ffi.cdef('''
enum InterceptionKeyState
{
    INTERCEPTION_KEY_DOWN,
    INTERCEPTION_KEY_UP,
    INTERCEPTION_KEY_E0,
    INTERCEPTION_KEY_E1,
    INTERCEPTION_KEY_TERMSRV_SET_LED,
    INTERCEPTION_KEY_TERMSRV_SHADOW,
    INTERCEPTION_KEY_TERMSRV_VKPACKET,
    ...
};

enum InterceptionFilterKeyState
{
    INTERCEPTION_FILTER_KEY_NONE,
    INTERCEPTION_FILTER_KEY_ALL,
    INTERCEPTION_FILTER_KEY_DOWN,
    INTERCEPTION_FILTER_KEY_UP,
    INTERCEPTION_FILTER_KEY_E0,
    INTERCEPTION_FILTER_KEY_E1,
    INTERCEPTION_FILTER_KEY_TERMSRV_SET_LED,
    INTERCEPTION_FILTER_KEY_TERMSRV_SHADOW,
    INTERCEPTION_FILTER_KEY_TERMSRV_VKPACKET,
    ...
};

enum InterceptionMouseState
{
    INTERCEPTION_MOUSE_LEFT_BUTTON_DOWN,
    INTERCEPTION_MOUSE_LEFT_BUTTON_UP,
    INTERCEPTION_MOUSE_RIGHT_BUTTON_DOWN,
    INTERCEPTION_MOUSE_RIGHT_BUTTON_UP,
    INTERCEPTION_MOUSE_MIDDLE_BUTTON_DOWN,
    INTERCEPTION_MOUSE_MIDDLE_BUTTON_UP,

    INTERCEPTION_MOUSE_BUTTON_1_DOWN,
    INTERCEPTION_MOUSE_BUTTON_1_UP,
    INTERCEPTION_MOUSE_BUTTON_2_DOWN,
    INTERCEPTION_MOUSE_BUTTON_2_UP,
    INTERCEPTION_MOUSE_BUTTON_3_DOWN,
    INTERCEPTION_MOUSE_BUTTON_3_UP,

    INTERCEPTION_MOUSE_BUTTON_4_DOWN,
    INTERCEPTION_MOUSE_BUTTON_4_UP,
    INTERCEPTION_MOUSE_BUTTON_5_DOWN,
    INTERCEPTION_MOUSE_BUTTON_5_UP,

    INTERCEPTION_MOUSE_WHEEL,
    INTERCEPTION_MOUSE_HWHEEL,
    ...
};

enum InterceptionFilterMouseState
{
    INTERCEPTION_FILTER_MOUSE_NONE,
    INTERCEPTION_FILTER_MOUSE_ALL,

    INTERCEPTION_FILTER_MOUSE_LEFT_BUTTON_DOWN,
    INTERCEPTION_FILTER_MOUSE_LEFT_BUTTON_UP,
    INTERCEPTION_FILTER_MOUSE_RIGHT_BUTTON_DOWN,
    INTERCEPTION_FILTER_MOUSE_RIGHT_BUTTON_UP,
    INTERCEPTION_FILTER_MOUSE_MIDDLE_BUTTON_DOWN,
    INTERCEPTION_FILTER_MOUSE_MIDDLE_BUTTON_UP,

    INTERCEPTION_FILTER_MOUSE_BUTTON_1_DOWN,
    INTERCEPTION_FILTER_MOUSE_BUTTON_1_UP,
    INTERCEPTION_FILTER_MOUSE_BUTTON_2_DOWN,
    INTERCEPTION_FILTER_MOUSE_BUTTON_2_UP,
    INTERCEPTION_FILTER_MOUSE_BUTTON_3_DOWN,
    INTERCEPTION_FILTER_MOUSE_BUTTON_3_UP,

    INTERCEPTION_FILTER_MOUSE_BUTTON_4_DOWN,
    INTERCEPTION_FILTER_MOUSE_BUTTON_4_UP,
    INTERCEPTION_FILTER_MOUSE_BUTTON_5_DOWN,
    INTERCEPTION_FILTER_MOUSE_BUTTON_5_UP,

    INTERCEPTION_FILTER_MOUSE_WHEEL,
    INTERCEPTION_FILTER_MOUSE_HWHEEL,

    INTERCEPTION_FILTER_MOUSE_MOVE,
    ...
};

enum InterceptionMouseFlag
{
    INTERCEPTION_MOUSE_MOVE_RELATIVE,
    INTERCEPTION_MOUSE_MOVE_ABSOLUTE,
    INTERCEPTION_MOUSE_VIRTUAL_DESKTOP,
    INTERCEPTION_MOUSE_ATTRIBUTES_CHANGED,
    INTERCEPTION_MOUSE_MOVE_NOCOALESCE,
    INTERCEPTION_MOUSE_TERMSRV_SRC_SHADOW,
    ...
};
''')

_is_64bits = sys.maxsize > 2 ** 32
lib = ffi.verify('''
#include "interception.h"
''', libraries=['interception64' if _is_64bits else 'interception'], tmpdir='.')
