from _interception import ffi, lib

'''
dlopen() can not auto fill enum values
this script is used to verify() declared enums and generate copy-pastable declarations with correct values
'''

# InterceptionKeyState
assert lib.INTERCEPTION_KEY_DOWN == 0x00
assert lib.INTERCEPTION_KEY_UP == 0x01
assert lib.INTERCEPTION_KEY_E0 == 0x02
assert lib.INTERCEPTION_KEY_E1 == 0x04
assert lib.INTERCEPTION_KEY_TERMSRV_SET_LED == 0x08
assert lib.INTERCEPTION_KEY_TERMSRV_SHADOW == 0x10
assert lib.INTERCEPTION_KEY_TERMSRV_VKPACKET == 0x20

# InterceptionFilterKeyState
assert lib.INTERCEPTION_FILTER_KEY_NONE == 0x0000
assert lib.INTERCEPTION_FILTER_KEY_ALL == 0xFFFF
assert lib.INTERCEPTION_FILTER_KEY_DOWN == lib.INTERCEPTION_KEY_UP
assert lib.INTERCEPTION_FILTER_KEY_UP == lib.INTERCEPTION_KEY_UP << 1
assert lib.INTERCEPTION_FILTER_KEY_E0 == lib.INTERCEPTION_KEY_E0 << 1
assert lib.INTERCEPTION_FILTER_KEY_E1 == lib.INTERCEPTION_KEY_E1 << 1
assert lib.INTERCEPTION_FILTER_KEY_TERMSRV_SET_LED == lib.INTERCEPTION_KEY_TERMSRV_SET_LED << 1
assert lib.INTERCEPTION_FILTER_KEY_TERMSRV_SHADOW == lib.INTERCEPTION_KEY_TERMSRV_SHADOW << 1
assert lib.INTERCEPTION_FILTER_KEY_TERMSRV_VKPACKET == lib.INTERCEPTION_KEY_TERMSRV_VKPACKET << 1

# InterceptionMouseState
assert lib.INTERCEPTION_MOUSE_LEFT_BUTTON_DOWN == 0x001
assert lib.INTERCEPTION_MOUSE_LEFT_BUTTON_UP == 0x002
assert lib.INTERCEPTION_MOUSE_RIGHT_BUTTON_DOWN == 0x004
assert lib.INTERCEPTION_MOUSE_RIGHT_BUTTON_UP == 0x008
assert lib.INTERCEPTION_MOUSE_MIDDLE_BUTTON_DOWN == 0x010
assert lib.INTERCEPTION_MOUSE_MIDDLE_BUTTON_UP == 0x020

assert lib.INTERCEPTION_MOUSE_BUTTON_1_DOWN == lib.INTERCEPTION_MOUSE_LEFT_BUTTON_DOWN
assert lib.INTERCEPTION_MOUSE_BUTTON_1_UP == lib.INTERCEPTION_MOUSE_LEFT_BUTTON_UP
assert lib.INTERCEPTION_MOUSE_BUTTON_2_DOWN == lib.INTERCEPTION_MOUSE_RIGHT_BUTTON_DOWN
assert lib.INTERCEPTION_MOUSE_BUTTON_2_UP == lib.INTERCEPTION_MOUSE_RIGHT_BUTTON_UP
assert lib.INTERCEPTION_MOUSE_BUTTON_3_DOWN == lib.INTERCEPTION_MOUSE_MIDDLE_BUTTON_DOWN
assert lib.INTERCEPTION_MOUSE_BUTTON_3_UP == lib.INTERCEPTION_MOUSE_MIDDLE_BUTTON_UP

assert lib.INTERCEPTION_MOUSE_BUTTON_4_DOWN == 0x040
assert lib.INTERCEPTION_MOUSE_BUTTON_4_UP == 0x080
assert lib.INTERCEPTION_MOUSE_BUTTON_5_DOWN == 0x100
assert lib.INTERCEPTION_MOUSE_BUTTON_5_UP == 0x200

assert lib.INTERCEPTION_MOUSE_WHEEL == 0x400
assert lib.INTERCEPTION_MOUSE_HWHEEL == 0x800

# InterceptionFilterMouseState
assert lib.INTERCEPTION_FILTER_MOUSE_NONE == 0x0000
assert lib.INTERCEPTION_FILTER_MOUSE_ALL == 0xFFFF

assert lib.INTERCEPTION_FILTER_MOUSE_LEFT_BUTTON_DOWN == lib.INTERCEPTION_MOUSE_LEFT_BUTTON_DOWN
assert lib.INTERCEPTION_FILTER_MOUSE_LEFT_BUTTON_UP == lib.INTERCEPTION_MOUSE_LEFT_BUTTON_UP
assert lib.INTERCEPTION_FILTER_MOUSE_RIGHT_BUTTON_DOWN == lib.INTERCEPTION_MOUSE_RIGHT_BUTTON_DOWN
assert lib.INTERCEPTION_FILTER_MOUSE_RIGHT_BUTTON_UP == lib.INTERCEPTION_MOUSE_RIGHT_BUTTON_UP
assert lib.INTERCEPTION_FILTER_MOUSE_MIDDLE_BUTTON_DOWN == lib.INTERCEPTION_MOUSE_MIDDLE_BUTTON_DOWN
assert lib.INTERCEPTION_FILTER_MOUSE_MIDDLE_BUTTON_UP == lib.INTERCEPTION_MOUSE_MIDDLE_BUTTON_UP

assert lib.INTERCEPTION_FILTER_MOUSE_BUTTON_1_DOWN == lib.INTERCEPTION_MOUSE_BUTTON_1_DOWN
assert lib.INTERCEPTION_FILTER_MOUSE_BUTTON_1_UP == lib.INTERCEPTION_MOUSE_BUTTON_1_UP
assert lib.INTERCEPTION_FILTER_MOUSE_BUTTON_2_DOWN == lib.INTERCEPTION_MOUSE_BUTTON_2_DOWN
assert lib.INTERCEPTION_FILTER_MOUSE_BUTTON_2_UP == lib.INTERCEPTION_MOUSE_BUTTON_2_UP
assert lib.INTERCEPTION_FILTER_MOUSE_BUTTON_3_DOWN == lib.INTERCEPTION_MOUSE_BUTTON_3_DOWN
assert lib.INTERCEPTION_FILTER_MOUSE_BUTTON_3_UP == lib.INTERCEPTION_MOUSE_BUTTON_3_UP

assert lib.INTERCEPTION_FILTER_MOUSE_BUTTON_4_DOWN == lib.INTERCEPTION_MOUSE_BUTTON_4_DOWN
assert lib.INTERCEPTION_FILTER_MOUSE_BUTTON_4_UP == lib.INTERCEPTION_MOUSE_BUTTON_4_UP
assert lib.INTERCEPTION_FILTER_MOUSE_BUTTON_5_DOWN == lib.INTERCEPTION_MOUSE_BUTTON_5_DOWN
assert lib.INTERCEPTION_FILTER_MOUSE_BUTTON_5_UP == lib.INTERCEPTION_MOUSE_BUTTON_5_UP

assert lib.INTERCEPTION_FILTER_MOUSE_WHEEL == lib.INTERCEPTION_MOUSE_WHEEL
assert lib.INTERCEPTION_FILTER_MOUSE_HWHEEL == lib.INTERCEPTION_MOUSE_HWHEEL

assert lib.INTERCEPTION_FILTER_MOUSE_MOVE == 0x1000

# InterceptionMouseFlag
assert lib.INTERCEPTION_MOUSE_MOVE_RELATIVE == 0x000
assert lib.INTERCEPTION_MOUSE_MOVE_ABSOLUTE == 0x001
assert lib.INTERCEPTION_MOUSE_VIRTUAL_DESKTOP == 0x002
assert lib.INTERCEPTION_MOUSE_ATTRIBUTES_CHANGED == 0x004
assert lib.INTERCEPTION_MOUSE_MOVE_NOCOALESCE == 0x008
assert lib.INTERCEPTION_MOUSE_TERMSRV_SRC_SHADOW == 0x100

print('''
enum InterceptionKeyState
{{
    INTERCEPTION_KEY_DOWN             = 0x{lib.INTERCEPTION_KEY_DOWN:02X},
    INTERCEPTION_KEY_UP               = 0x{lib.INTERCEPTION_KEY_UP:02X},
    INTERCEPTION_KEY_E0               = 0x{lib.INTERCEPTION_KEY_E0:02X},
    INTERCEPTION_KEY_E1               = 0x{lib.INTERCEPTION_KEY_E1:02X},
    INTERCEPTION_KEY_TERMSRV_SET_LED  = 0x{lib.INTERCEPTION_KEY_TERMSRV_SET_LED:02X},
    INTERCEPTION_KEY_TERMSRV_SHADOW   = 0x{lib.INTERCEPTION_KEY_TERMSRV_SHADOW:02X},
    INTERCEPTION_KEY_TERMSRV_VKPACKET = 0x{lib.INTERCEPTION_KEY_TERMSRV_VKPACKET:02X}
}};

enum InterceptionFilterKeyState
{{
    INTERCEPTION_FILTER_KEY_NONE             = 0x{lib.INTERCEPTION_FILTER_KEY_NONE:02X},
    INTERCEPTION_FILTER_KEY_ALL              = 0x{lib.INTERCEPTION_FILTER_KEY_ALL:02X},
    INTERCEPTION_FILTER_KEY_DOWN             = 0x{lib.INTERCEPTION_FILTER_KEY_DOWN:02X},
    INTERCEPTION_FILTER_KEY_UP               = 0x{lib.INTERCEPTION_FILTER_KEY_UP:02X},
    INTERCEPTION_FILTER_KEY_E0               = 0x{lib.INTERCEPTION_FILTER_KEY_E0:02X},
    INTERCEPTION_FILTER_KEY_E1               = 0x{lib.INTERCEPTION_FILTER_KEY_E1:02X},
    INTERCEPTION_FILTER_KEY_TERMSRV_SET_LED  = 0x{lib.INTERCEPTION_FILTER_KEY_TERMSRV_SET_LED:02X},
    INTERCEPTION_FILTER_KEY_TERMSRV_SHADOW   = 0x{lib.INTERCEPTION_FILTER_KEY_TERMSRV_SHADOW:02X},
    INTERCEPTION_FILTER_KEY_TERMSRV_VKPACKET = 0x{lib.INTERCEPTION_FILTER_KEY_TERMSRV_VKPACKET:02X}
}};

enum InterceptionMouseState
{{
    INTERCEPTION_MOUSE_LEFT_BUTTON_DOWN   = 0x{lib.INTERCEPTION_MOUSE_LEFT_BUTTON_DOWN:02X},
    INTERCEPTION_MOUSE_LEFT_BUTTON_UP     = 0x{lib.INTERCEPTION_MOUSE_LEFT_BUTTON_UP:02X},
    INTERCEPTION_MOUSE_RIGHT_BUTTON_DOWN  = 0x{lib.INTERCEPTION_MOUSE_RIGHT_BUTTON_DOWN:02X},
    INTERCEPTION_MOUSE_RIGHT_BUTTON_UP    = 0x{lib.INTERCEPTION_MOUSE_RIGHT_BUTTON_UP:02X},
    INTERCEPTION_MOUSE_MIDDLE_BUTTON_DOWN = 0x{lib.INTERCEPTION_MOUSE_MIDDLE_BUTTON_DOWN:02X},
    INTERCEPTION_MOUSE_MIDDLE_BUTTON_UP   = 0x{lib.INTERCEPTION_MOUSE_MIDDLE_BUTTON_UP:02X},

    INTERCEPTION_MOUSE_BUTTON_1_DOWN      = 0x{lib.INTERCEPTION_MOUSE_BUTTON_1_DOWN:02X},
    INTERCEPTION_MOUSE_BUTTON_1_UP        = 0x{lib.INTERCEPTION_MOUSE_BUTTON_1_UP:02X},
    INTERCEPTION_MOUSE_BUTTON_2_DOWN      = 0x{lib.INTERCEPTION_MOUSE_BUTTON_2_DOWN:02X},
    INTERCEPTION_MOUSE_BUTTON_2_UP        = 0x{lib.INTERCEPTION_MOUSE_BUTTON_2_UP:02X},
    INTERCEPTION_MOUSE_BUTTON_3_DOWN      = 0x{lib.INTERCEPTION_MOUSE_BUTTON_3_DOWN:02X},
    INTERCEPTION_MOUSE_BUTTON_3_UP        = 0x{lib.INTERCEPTION_MOUSE_BUTTON_3_UP:02X},

    INTERCEPTION_MOUSE_BUTTON_4_DOWN      = 0x{lib.INTERCEPTION_MOUSE_BUTTON_4_DOWN:02X},
    INTERCEPTION_MOUSE_BUTTON_4_UP        = 0x{lib.INTERCEPTION_MOUSE_BUTTON_4_UP:02X},
    INTERCEPTION_MOUSE_BUTTON_5_DOWN      = 0x{lib.INTERCEPTION_MOUSE_BUTTON_5_DOWN:02X},
    INTERCEPTION_MOUSE_BUTTON_5_UP        = 0x{lib.INTERCEPTION_MOUSE_BUTTON_5_UP:02X},

    INTERCEPTION_MOUSE_WHEEL              = 0x{lib.INTERCEPTION_MOUSE_WHEEL:02X},
    INTERCEPTION_MOUSE_HWHEEL             = 0x{lib.INTERCEPTION_MOUSE_HWHEEL:02X}
}};

enum InterceptionFilterMouseState
{{
    INTERCEPTION_FILTER_MOUSE_NONE               = 0x{lib.INTERCEPTION_FILTER_MOUSE_NONE:02X},
    INTERCEPTION_FILTER_MOUSE_ALL                = 0x{lib.INTERCEPTION_FILTER_MOUSE_ALL:02X},

    INTERCEPTION_FILTER_MOUSE_LEFT_BUTTON_DOWN   = 0x{lib.INTERCEPTION_FILTER_MOUSE_LEFT_BUTTON_DOWN:02X},
    INTERCEPTION_FILTER_MOUSE_LEFT_BUTTON_UP     = 0x{lib.INTERCEPTION_FILTER_MOUSE_LEFT_BUTTON_UP:02X},
    INTERCEPTION_FILTER_MOUSE_RIGHT_BUTTON_DOWN  = 0x{lib.INTERCEPTION_FILTER_MOUSE_RIGHT_BUTTON_DOWN:02X},
    INTERCEPTION_FILTER_MOUSE_RIGHT_BUTTON_UP    = 0x{lib.INTERCEPTION_FILTER_MOUSE_RIGHT_BUTTON_UP:02X},
    INTERCEPTION_FILTER_MOUSE_MIDDLE_BUTTON_DOWN = 0x{lib.INTERCEPTION_FILTER_MOUSE_MIDDLE_BUTTON_DOWN:02X},
    INTERCEPTION_FILTER_MOUSE_MIDDLE_BUTTON_UP   = 0x{lib.INTERCEPTION_FILTER_MOUSE_MIDDLE_BUTTON_UP:02X},

    INTERCEPTION_FILTER_MOUSE_BUTTON_1_DOWN      = 0x{lib.INTERCEPTION_FILTER_MOUSE_BUTTON_1_DOWN:02X},
    INTERCEPTION_FILTER_MOUSE_BUTTON_1_UP        = 0x{lib.INTERCEPTION_FILTER_MOUSE_BUTTON_1_UP:02X},
    INTERCEPTION_FILTER_MOUSE_BUTTON_2_DOWN      = 0x{lib.INTERCEPTION_FILTER_MOUSE_BUTTON_2_DOWN:02X},
    INTERCEPTION_FILTER_MOUSE_BUTTON_2_UP        = 0x{lib.INTERCEPTION_FILTER_MOUSE_BUTTON_2_UP:02X},
    INTERCEPTION_FILTER_MOUSE_BUTTON_3_DOWN      = 0x{lib.INTERCEPTION_FILTER_MOUSE_BUTTON_3_DOWN:02X},
    INTERCEPTION_FILTER_MOUSE_BUTTON_3_UP        = 0x{lib.INTERCEPTION_FILTER_MOUSE_BUTTON_3_UP:02X},

    INTERCEPTION_FILTER_MOUSE_BUTTON_4_DOWN      = 0x{lib.INTERCEPTION_FILTER_MOUSE_BUTTON_4_DOWN:02X},
    INTERCEPTION_FILTER_MOUSE_BUTTON_4_UP        = 0x{lib.INTERCEPTION_FILTER_MOUSE_BUTTON_4_UP:02X},
    INTERCEPTION_FILTER_MOUSE_BUTTON_5_DOWN      = 0x{lib.INTERCEPTION_FILTER_MOUSE_BUTTON_5_DOWN:02X},
    INTERCEPTION_FILTER_MOUSE_BUTTON_5_UP        = 0x{lib.INTERCEPTION_FILTER_MOUSE_BUTTON_5_UP:02X},

    INTERCEPTION_FILTER_MOUSE_WHEEL              = 0x{lib.INTERCEPTION_FILTER_MOUSE_WHEEL:02X},
    INTERCEPTION_FILTER_MOUSE_HWHEEL             = 0x{lib.INTERCEPTION_FILTER_MOUSE_HWHEEL:02X},

    INTERCEPTION_FILTER_MOUSE_MOVE               = 0x{lib.INTERCEPTION_FILTER_MOUSE_MOVE:02X}
}};

enum InterceptionMouseFlag
{{
    INTERCEPTION_MOUSE_MOVE_RELATIVE      = 0x{lib.INTERCEPTION_MOUSE_MOVE_RELATIVE:02X},
    INTERCEPTION_MOUSE_MOVE_ABSOLUTE      = 0x{lib.INTERCEPTION_MOUSE_MOVE_ABSOLUTE:02X},
    INTERCEPTION_MOUSE_VIRTUAL_DESKTOP    = 0x{lib.INTERCEPTION_MOUSE_VIRTUAL_DESKTOP:02X},
    INTERCEPTION_MOUSE_ATTRIBUTES_CHANGED = 0x{lib.INTERCEPTION_MOUSE_ATTRIBUTES_CHANGED:02X},
    INTERCEPTION_MOUSE_MOVE_NOCOALESCE    = 0x{lib.INTERCEPTION_MOUSE_MOVE_NOCOALESCE:02X},
    INTERCEPTION_MOUSE_TERMSRV_SRC_SHADOW = 0x{lib.INTERCEPTION_MOUSE_TERMSRV_SRC_SHADOW:02X}
}};'''.format(lib=lib))
