name: Build

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - "docs/**"
      - "*.md"


permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  sdist:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: build sdist
        run: |
          python -m pip install build
          python -m build --sdist

      - name: upload sdist artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist
          if-no-files-found: error

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12", "3.13.0-alpha.2" ]
        architecture: [ "x86", "x64" ]
        os: [ windows-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install build

      - name: build wheel
        run: |
          python -m build --wheel

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: dist
          if-no-files-found: error
